<a href="https://colab.research.google.com/github/SanjibKarunaChaitanyaGhosh/Machine-Learning-Model/blob/main/Machine_Learning_breast_cancer_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Link Kaggle dataset with collab without download datasets

In [203]:
!pip install kaggle

In [204]:
!kaggle datasets download -d uciml/breast-cancer-wisconsin-data

Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
License(s): CC-BY-NC-SA-4.0
breast-cancer-wisconsin-data.zip: Skipping, found more recently modified local copy (use --force to force download)


# 2. Import DATASET

In [205]:
import numpy as np
import pandas as pd

In [206]:
breast = pd.read_csv("/content/breast-cancer-wisconsin-data.zip")

In [207]:
breast.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


**Benign** -- > Cancer Positive                                  
**Malignant** --> Cancer Negative

In [208]:
breast['diagnosis'].value_counts()

,count
diagnosis,
B,357
M,212


# 3. ASK six questions



In [209]:
breast.shape

(569, 33)

In [210]:
breast.isnull().sum()

,0
id,0
diagnosis,0
radius_mean,0
texture_mean,0
perimeter_mean,0
area_mean,0
smoothness_mean,0
compactness_mean,0
concavity_mean,0
concave points_mean,0


In [211]:
breast.drop('Unnamed: 32',axis=1,inplace=True)

In [212]:
breast.shape

(569, 32)

In [213]:
breast.duplicated().sum()

np.int64(0)

In [214]:
breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

# 4. Encoding The Target Varible

## from sklearn.preprocessing import LabelEncoder
## le = LabelEncoder()

In [215]:
breast['diagnosis'] = breast['diagnosis'].map({'M':'1','B':'0'})

In [216]:
breast.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [217]:
breast.corr()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
id,1.000000,0.039769,0.074626,0.099770,0.073159,0.096893,-0.012968,0.000096,0.050080,0.044158,...,0.082405,0.064720,0.079986,0.107187,0.010338,-0.002968,0.023203,0.035174,-0.044224,-0.029866
diagnosis,0.039769,1.000000,0.730029,0.415185,0.742636,0.708984,0.358560,0.596534,0.696360,0.776614,...,0.776454,0.456903,0.782914,0.733825,0.421465,0.590998,0.659610,0.793566,0.416294,0.323872
radius_mean,0.074626,0.730029,1.000000,0.323782,0.997855,0.987357,0.170581,0.506124,0.676764,0.822529,...,0.969539,0.297008,0.965137,0.941082,0.119616,0.413463,0.526911,0.744214,0.163953,0.007066
texture_mean,0.099770,0.415185,0.323782,1.000000,0.329533,0.321086,-0.023389,0.236702,0.302418,0.293464,...,0.352573,0.912045,0.358040,0.343546,0.077503,0.277830,0.301025,0.295316,0.105008,0.119205
perimeter_mean,0.073159,0.742636,0.997855,0.329533,1.000000,0.986507,0.207278,0.556936,0.716136,0.850977,...,0.969476,0.303038,0.970387,0.941550,0.150549,0.455774,0.563879,0.771241,0.189115,0.051019
area_mean,0.096893,0.708984,0.987357,0.321086,0.986507,1.000000,0.177028,0.498502,0.685983,0.823269,...,0.962746,0.287489,0.959120,0.959213,0.123523,0.390410,0.512606,0.722017,0.143570,0.003738
smoothness_mean,-0.012968,0.358560,0.170581,-0.023389,0.207278,0.177028,1.000000,0.659123,0.521984,0.553695,...,0.213120,0.036072,0.238853,0.206718,0.805324,0.472468,0.434926,0.503053,0.394309,0.499316
compactness_mean,0.000096,0.596534,0.506124,0.236702,0.556936,0.498502,0.659123,1.000000,0.883121,0.831135,...,0.535315,0.248133,0.590210,0.509604,0.565541,0.865809,0.816275,0.815573,0.510223,0.687382
concavity_mean,0.050080,0.696360,0.676764,0.302418,0.716136,0.685983,0.521984,0.883121,1.000000,0.921391,...,0.688236,0.299879,0.729565,0.675987,0.448822,0.754968,0.884103,0.861323,0.409464,0.514930
concave points_mean,0.044158,0.776614,0.822529,0.293464,0.850977,0.823269,0.553695,0.831135,0.921391,1.000000,...,0.830318,0.292752,0.855923,0.809630,0.452753,0.667454,0.752399,0.910155,0.375744,0.368661


# 5. Splitting Data into Training and Testing Sets

In [218]:
breast.shape

(569, 32)

In [219]:
X = breast.drop('diagnosis',axis=1)
y = breast['diagnosis']

In [220]:
X.shape

(569, 31)

In [221]:
y.shape

(569,)

In [222]:
from sklearn.model_selection import train_test_split

In [223]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [224]:
X_train.shape

(455, 31)

In [225]:
X_test.shape

(114, 31)

In [226]:
X_train

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
68,859471,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.04375,0.2111,...,10.310,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
181,873593,21.090,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,...,26.680,33.48,176.50,2089.0,0.14910,0.75840,0.67800,0.29030,0.4098,0.12840
63,859196,9.173,13.86,59.20,260.9,0.07721,0.08751,0.05988,0.02180,0.2341,...,10.010,19.23,65.59,310.1,0.09836,0.16780,0.13970,0.05087,0.3282,0.08490
248,88466802,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.01615,0.1897,...,12.250,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147
60,858970,10.170,14.88,64.55,311.9,0.11340,0.08061,0.01084,0.01290,0.2743,...,11.020,17.45,69.86,368.6,0.12750,0.09866,0.02168,0.02579,0.3557,0.08020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,859711,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.02872,0.1902,...,9.733,15.67,62.56,284.4,0.12070,0.24360,0.14340,0.04786,0.2254,0.10840
106,863031,11.640,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,...,13.140,29.26,85.51,521.7,0.16880,0.26600,0.28730,0.12180,0.2806,0.09097
270,8910721,14.290,16.82,90.30,632.6,0.06429,0.02675,0.00725,0.00625,0.1508,...,14.910,20.65,94.44,684.6,0.08567,0.05036,0.03866,0.03333,0.2458,0.06120
435,908489,13.980,19.62,91.12,599.5,0.10600,0.11330,0.11260,0.06463,0.1669,...,17.040,30.80,113.90,869.3,0.16130,0.35680,0.40690,0.18270,0.3179,0.10550


# 6. Feature Scaling

In [227]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [228]:
sc.fit(X_train)

StandardScaler()

In [229]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [230]:
X_test

array([[-0.24295555, -0.46649743, -0.13728933, ..., -0.19435087,
         0.17275669,  0.20372995],
       [-0.23712621,  1.36536344,  0.49866473, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [-0.24355432,  0.38006578,  0.06921974, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.23693649, -0.73547237, -0.99852603, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [-0.23694721,  0.02898271,  2.0334026 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 0.42868759,  1.87216885,  2.80077153, ...,  0.7925579 ,
        -0.05868885, -0.09467243]])

In [231]:
X_train

array([[-0.23712699, -1.44075296, -0.43531947, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [-0.23702031,  1.97409619,  1.73302577, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-0.23712907, -1.39998202, -1.24962228, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [-0.17630431,  0.04880192, -0.55500086, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.23675669, -0.03896885,  0.10207345, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.2371006 , -0.54860557,  0.31327591, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

# 7. Training Model

In [232]:
from sklearn.linear_model import LogisticRegression

In [233]:
lg=LogisticRegression()

In [234]:
lg.fit(X_train,y_train)

LogisticRegression()

In [235]:
y_pred = lg.predict(X_test)

In [236]:
y_pred

array(['0', '1', '1', '0', '0', '1', '1', '1', '0', '0', '0', '1', '0',
       '1', '0', '1', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1',
       '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1',
       '0', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '0', '0',
       '0', '1', '1', '0', '0', '1', '1', '0', '1', '0', '0', '0', '0',
       '0', '0', '1', '0', '1', '1', '1', '1', '1', '1', '0', '0', '0',
       '0', '0', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1', '1',
       '0', '0', '0', '1', '0', '0', '1', '0', '1', '1'], dtype=object)

## Comparing

In [237]:
from sklearn.metrics import accuracy_score

In [238]:
accuracy_score(y_test,y_pred)

0.9736842105263158

#8. Prediction System

In [239]:
X_train[0]

array([-0.23712699, -1.44075296, -0.43531947, -1.36208497, -1.1391179 ,
        0.78057331,  0.71892128,  2.82313451, -0.11914956,  1.09266219,
        2.45817261, -0.26380039, -0.01605246, -0.47041357, -0.47476088,
        0.83836493,  3.25102691,  8.43893667,  3.39198733,  2.62116574,
        2.06120787, -1.23286131, -0.47630949, -1.24792009, -0.97396758,
        0.72289445,  1.18673232,  4.67282796,  0.9320124 ,  2.09724217,
        1.88645014])

In [243]:
X_test[2]

array([-0.24355432,  0.38006578,  0.06921974,  0.40410139,  0.26659607,
        0.96752014,  0.35641445,  0.72690205,  0.85722095,  0.43709369,
       -0.66605282,  0.25555697, -0.77018483,  0.11394607,  0.17460653,
       -0.24531887, -0.58082836, -0.14617367, -0.15331827, -0.80895985,
       -0.48829815,  0.62940306,  0.07663816,  0.53383214,  0.49204412,
        1.00046591, -0.08616295,  0.4996247 ,  0.57035018, -0.10783139,
       -0.20629287])

In [244]:
y_test[2]


'1'

In [250]:
input_text = [-0.23712699, -1.44075296, -0.43531947, -1.36208497, -1.1391179 ,
        0.78057331,  0.71892128,  2.82313451, -0.11914956,  1.09266219,
        2.45817261, -0.26380039, -0.01605246, -0.47041357, -0.47476088,
        0.83836493,  3.25102691,  8.43893667,  3.39198733,  2.62116574,
        2.06120787, -1.23286131, -0.47630949, -1.24792009, -0.97396758,
        0.72289445,  1.18673232,  4.67282796,  0.9320124 ,  2.09724217,
        1.88645014]
np_df=np.asanyarray(input_text)
prediction  = lg.predict(np_df.reshape(1,-1))
print(prediction)
print(type(prediction[0]))
if prediction[0]=='1':
  print("Cancrous")
else :
  print("Not Cancrous")

['0']
<class 'str'>
Not Cancrous


# 1 = Cancerous (Malignant)
# 0 = Not Cancerous (Benign)

In [246]:
print(np.unique(y_train))

['0' '1']


In [247]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

print(data.target_names)

['malignant' 'benign']


# 10. Pickle



In [248]:
import pickle
pickle.dump(lg,open("model.pkl","wb"))